language: python
python:
- '3.6'
install:
- pip install ansible>=2.4.0 molecule apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: hSYnB8WrVHGwNslSfv24tsiFkw9n66tbmtIH98IEWM3DJMSHG8RCSjpPuF1RKvlN5977ktHAOAq7XIQ77UvdqjlUNAlZJS/PFgRjlkHIg5I9YoaHSIhFN9OvmGlqEWvoaukSw8/bf39tquhVr9AUQdcvblxQKvPdPqE91DS+INcHkPJKep2z+HfW8nBrahWDZ9he+tTYvLxMUMlFsFBG5Lwzq9Mm2oK8N/eB+UnYIKW++xqYfIk7IOygqdduWrLXbS4PeHE0PuJCH3cbKgtJ0Uq7Byh5SfI2wG0xIyT14sGWWOoojBphDZGNZXNQ99yD3V8kBJBHYEuXr3rGHz0tcECFQ8rgWcQSr334HZ8MN0Gvj68Quj7pSv6oJTpIAAvw69dFdKI07Syattajns/0/GCgmQhX/AssCspr/EVVrnxhtn4d9mnmcV3YvpXgWzNP5B1D793v2JyJQ5ySIx8qZX1isDoxpRr+Pj9vS/fajqEHozHJMneKLHYc4+zii+xwoFfhorAB3LBgthwl1MA8pr6NS/RhWnPbFJPkvn5Rzcw2JJQWu4tLHCXB6moFMWGGg60dtmIhsZwyOd2bPgP47EyFsX4Gt8oAra//vJ1PSai7CxnxNwmZ5xU7GF2He0hqdI4MxXc44kpsxITLiAm34NQr51R7i9WzdkN+YHj+Rss=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_1509c37ab118_key -iv $encrypted_1509c37ab118_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: EfN+04ESd35F6rHrnJl36sytILFivisIlKRUat0T27kEEheIGYLm9EbUDKgHsGi6doZzEBhx/o3IzSPRLxvym4E4TpWu0DnQUTTuxHqgfWp9DLcUsVjIuiP6hNuGVItVA1lnHzjTyibnb3l7z+Sd+rbkX6lXuEaU4aEW/B6UMBXwxfGwNbmHBH4+sDO+y5xVE64/2F6CNXrtfqLxCA0PehW9aqdEXFiSdr3fQxDlAUWWIdVA+A+FEqS23LQShknQkWaFM/QklAqJ1NduPrZ/gZpfiZrXwFp3mXEH+SEhoGiLlDh8tWqJKQ1VV5cSz5BBbz8/TvpXg8DVivLnY/3TXhs6dX1G75CDCplBPWNwetvz0E+zXt9ygf120XNR7l4PcQmd9GpEOqoIgD5ry0Dxmg1O48tcfxfY3pBJacfUcFic+20v54OW5PPhW7l+Eodw4AEyqJmfgtkE86HDVFjIXUjUaJZPg+veCAgEj8fc5oqEdPHQ0QO02UJqqo20oBmfffy1/ks7BvkU6C6vCDytcgDX2X8iiI9HKYE2yNC03VU2ENdgLidvsrnFI8peUwzBFyOvXI5Ig2XzOKPPGZ5MWww1VPmsftg/LTOhBbMSxvfDolSwRxUPLvNxwjwaf25bGk+UHBbFOmVT7c+1DAfmpsE1r5drPlSUH72kn2P4W6s=
